import subprocess
import os

class TestRunner:
    """
    Automatically generates pytest files from test cases
    and runs them, collecting results.
    """
    
    def generate_pytest_file(self, test_cases: list[dict], output_path: str):
        """
        Convert our test case dicts into actual runnable pytest code.
        """
        lines = [
            '"""Auto-generated by AI Test-Case Generator"""',
            'import pytest',
            '',
        ]
        
        for tc in test_cases:
            func_name = tc['id'].lower() + "_" + tc['title'].lower()
            func_name = func_name.replace(" ", "_").replace("-", "_")
            func_name = ''.join(c for c in func_name if c.isalnum() or c == '_')
            
            lines.append(f'def test_{func_name}():')
            lines.append(f'    """')
            lines.append(f'    {tc["title"]}')
            lines.append(f'    Priority: {tc["priority"]} | Type: {tc["test_type"]}')
            lines.append(f'    Preconditions: {tc["preconditions"]}')
            lines.append(f'    Expected: {tc["expected_result"]}')
            lines.append(f'    """')
            for step in tc.get("steps", []):
                lines.append(f'    # {step}')
            lines.append(f'    assert True  # Replace with actual assertion')
            lines.append('')
        
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))
        
        print(f"📝 Generated pytest file: {output_path}")
    
    def run_tests(self, test_file: str, report_path: str) -> dict:
        """
        Run pytest and generate an HTML report.
        """
        # ✅ Always work with absolute paths
        abs_test_file = os.path.abspath(test_file)
        abs_report_path = os.path.abspath(report_path)

        # ✅ Create reports folder
        os.makedirs(os.path.dirname(abs_report_path), exist_ok=True)

        # ✅ Create __init__.py so pytest can find the test file
        init_file = os.path.join(os.path.dirname(abs_test_file), "__init__.py")
        if not os.path.exists(init_file):
            open(init_file, 'w').close()
            
        
        venv_python = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),"venv", "Scripts", "python.exe")

        cmd = [
             venv_python,
            "-m", "pytest",
            abs_test_file,
            f"--html={abs_report_path}",
            "--self-contained-html",
            "-v",
            "--tb=short",
            "--no-header",
            "-p", "no:cacheprovider"   # ✅ Avoid cache issues on Windows
        ]
        
        print(f"🚀 Running tests...")
        print(f"📁 Test file: {abs_test_file}")
        print(f"📁 Report path: {abs_report_path}")

        # ✅ KEY FIX: Run from project root, NOT from test folder
        project_root = os.path.abspath(
            os.path.join(os.path.dirname(abs_test_file), "..", "..")
        )

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=project_root
        )
        
        # ✅ Always print pytest output so you can see what happened
        print("\n--- pytest output ---")
        print(result.stdout)
        if result.stderr:
            print("STDERR:", result.stderr)
        print("--- end pytest output ---\n")

        output = result.stdout + result.stderr
        passed = output.count(" PASSED")
        failed = output.count(" FAILED")

        if os.path.exists(abs_report_path):
            print(f"✅ Report created successfully!")
        else:
            print(f"⚠️  Report still not found. Check pytest output above.")

        print(f"📊 Results: {passed} passed, {failed} failed")
        
        return {
            "passed": passed,
            "failed": failed,
            "total": passed + failed,
            "output": output
        }